### ISSUE TITLE
Running MultiBit from a USB version 0.5.9

### ISSUE THREAD

**Issue by soslug** [jim618/multibit#119]
Bug report
  Operating System: Ubuntu 12.04 LTS 64bit
  MultiBit Version: 0.5.9 however this problem was seen on other versions
  Java Version used openjdk-7-jre
Steps to replicate the problem: 
  

1. Insert USB drive after PC is turn on and in desktop this causes the filemanager to launch
2. open a console and navigate to usb drive
3. download installer into usb drive
4. change directory via console to usb drive
5. run command java -jar multibit-0.5.9-linux.jar
6. change install path to that of the usb my case /media/MULTIBIT/MultiBit-0.5.9
7. switch off setup shortcuts do not need them
8. finish installation
9. change flag permissions to allow executable
10. create a file called multibit.properties thus
11. touch MultiBit-0.5.9/multibit.properties
12. via the console and still within usb directory launch executable
java -jar MultiBit-0.5.9/multibit-exe.jar

After every instance the only place MultiBit directory is made is in the /home/user directory I do not seem able to change this. My MultiBit directory is on the same USB as the executable directory thus:-

MultiBit
MultiBit-0.5.9

Following these instructions below it should have been possible to run MultiBit from a USB key where the data is also stored.

Linux

Installing MultiBit to run on a USB drive for Linux.

Insert your USB drive into your Linux machine.
Run the MultiBit Linux installer. On the screen with the question "Select the installation path:" click on the "Browse" button and select a directory on your USB drive.
Run the rest of the installation as normal.
Once the installation is done, navigate to your USB drive's MultiBit installation directory. It is the directory with the "multibit-exe.jar" file.
Create a new text file called (exactly) "multibit.properties". Leave the file empty. This is the MultiBit configuration file. Having a copy in the installation directory (rather than the user's application data) tells MultiBit to run locally.
To run MultiBit locally, double click on the multibit-exe.jar. If this does not start up the jar file, open a command line to your installation directory and run "java -jar multibit-exe.jar".

Try as I might the ONLY place MultiBit directory installs to is the linux /home/user directory and nowhere else despite the addition of an empty file as specified above.

**Comment by gary-rowe** [comment]
[MBHD does not support running from USB](https://multibit.org/en/help/hd0.1/backups.html). Closing.
