### ISSUE TITLE
Wallet balances not selectable/copyable

### ISSUE THREAD

**Issue by dkisselev** [jim618/multibit#138]
I'm not sure how difficult this would be to do in Java (I mostly work in C#), but it would be great if it were possible to select and copy at least the total balance for a wallet (shown in the top left corner), and ideally the balance for each address.

It's a little tedious having to manually type out the entire balance of my wallet whenever I'd like to either send it all somewhere or plug it into excel/elsewhere for some math.

**Comment by gary-rowe** [comment]
[MBHD has an empty wallet tool](https://multibit.org/en/help/hd0.1/empty-wallet.html). Closing.
