### ISSUE TITLE
Cannot sync in full (Computer date set to past)

### ISSUE THREAD

**Issue by Funky911** [jim618/multibit#158]
I tried and upgraded to the latest version of MultiBit, however with the issue remains. It says "Synchronizing with network", connected to 4 peers and stuck to:

Number of blocks: 240,446
Date of last block: 08 Jun 2013 21:30

What should I do so my client syncs fully? Thanks.

PS: Also, when I synced today it went very slowly not as usual. Guys, is there any network problem ongoing these days?

**Comment by gary-rowe** [comment]
MBHD supports an NTP check to verify correct system time. Closing.
