### ISSUE TITLE
Cleaner update path

### ISSUE THREAD

**Issue by Forage** [jim618/multibit#214]
Hi,

Would it be an idea to implement a cleaner update path? When I'm updating to a new MultiBit release I now have to perform the following steps each time (on Linux):

- Run the installer
- Change the installation location to use /opt instead of /home/user
- Uninstall the previous release

It would be quite helpful to have the installer recognize the previous installation, use that location (or at least the parent folder) and remove the previous version.

Because the installer specifically includes the version in the install location by default, I am a bit reluctant to install a new release over an old one, i.e. use the same install location as the previous release. Is it OK to install to the old location?

Note that I'm not taking about some auto-update feature. That would be an option as well, but less of a priority if you ask me.

**Comment by gary-rowe** [comment]
The Install4j installer handles upgrades much better now. Closing.
