### ISSUE TITLE
Opening a wallet does not list it in wallets pane

### ISSUE THREAD

**Issue by venil7** [jim618/multibit#319]
Bug report
  Operating System: linux mint
  MultiBit Version: 0.5.14
  Steps to replicate the problem:

when opening a wallet via `File->Open` Wallet, the corresponding list item does not appear in wallets pane, until one opens more wallets.

![mbit](https://f.cloud.github.com/assets/508022/1509419/a55cb50c-4a49-11e3-8cd0-3866edd158da.jpg)

**Comment by gary-rowe** [comment]
Closing since this is likely to have been fixed in 0.5.18.
