### ISSUE TITLE
Crash when adding password to a wallet

### ISSUE THREAD

**Issue by YoranBrondsema** [jim618/multibit#325]
Hi,

I'm using MultiBit on an OpenSuse Linux distribution with OpenJDK (JRE version: OpenJDK Runtime Environment (7.0_45-b31) (build 1.7.0_45-b31)). I tried adding a password to a wallet but when I click on the "Add password to wallet" button after having filled in a password, the JVM crashes with the following output.

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f97ec7d06a0, pid=588, tid=140289289742080
#
# JRE version: OpenJDK Runtime Environment (7.0_45-b31) (build 1.7.0_45-b31)
# Java VM: OpenJDK 64-Bit Server VM (24.45-b08 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0x12d6a0]  __memcpy_ssse3+0x90
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /tmp/jvm-588/hs_error.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   http://icedtea.classpath.org/bugzilla
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted
```

**Comment by Vidreven** [comment]
Ok, the proposed solution works. You just have to be in the MultiBit install folder "/path/to/MultiBit-0.5.18".

**Comment by gary-rowe** [comment]
Thanks for the update. I think it's worth adding this to the main site as an article so I've raised an issue accordingly.

**Comment by gary-rowe** [comment]
Information is presented on every Linux download in the [installation instructions](https://multibit.org/en/help/hd0.1/how-to-install-linux.html). Closing.
