### ISSUE TITLE
Import wallet.json from blockchain missing addresses

### ISSUE THREAD

**Issue by xmurobi** [jim618/multibit#374]
I had imported wallet_test.json downloaded from blockchain which keys array looks like this(replace the priv use 'XXX'), and both this two addrs have money:

{"addr":"16Ng8gbbUnpxYffxRn27NEorUS6Ezzj6vv","priv":"XXX","created_time":0,"created_device_name":"javascript_web","created_device_version":"1.0","label":"aaa"},
{"addr":"18bBTkmhkkix1GgRXDsqpDsf6hREATQRxc","priv":"XXX","created_time":0,"created_device_name":"javascript_web","created_device_version":"1.0","label":"test"}

But after finished I only found one addr named test (18bBTkmhkkix1GgRXDsqpDsf6hREATQRxc) had been imported, the other (16Ng8gbbUnpxYffxRn27NEorUS6Ezzj6vv) doesn't. 

The related multibit.log show:
========================================================
08:47:55.652 [AWT-EventQueue-0] DEBUG o.m.v.s.a.ImportPrivateKeysSubmitAction - Importing from file '/Users/ABC/Documents/btc/wallet_test.json'. 
08:47:55.652 [AWT-EventQueue-0] DEBUG o.m.v.s.a.ImportPrivateKeysSubmitAction - MyWallet unencrypted wallet backup import. 
08:47:55.652 [AWT-EventQueue-0] DEBUG o.m.v.s.a.ImportPrivateKeysSubmitAction - Imported file contents length was 727 
08:47:55.655 [AWT-EventQueue-0] DEBUG o.m.v.s.a.ImportPrivateKeysSubmitAction - MyWallet wallet.2 = com.piuk.blockchain.MyWallet@61e90abf 
08:47:55.673 [AWT-EventQueue-0] DEBUG o.m.v.s.a.ImportPrivateKeysSubmitAction - bitcoinj wallet.2 = Wallet containing 0.00 BTC in:
  0 unspent transactions
  0 spent transactions
  0 pending transactions
  0 dead transactions
Last seen best block: (0) null

Keys:
  addr:19KniQUzkLvfKLFa6Ha3KPUKr16ZGY96tK pub:04558bcaded4ffba8e52cf74a93d039d8eaf68bf71be72fec8f925919b18f4746be9a5a1e38b39b874e458be0c60327a0d737c2bb13d2e7f31cfeb9b6997095d0c
  addr:18bBTkmhkkix1GgRXDsqpDsf6hREATQRxc pub:042885f45b03299f98045f2964cfde460eca0143fee8ce57fac9ba7fe4a809bc2d95828fa89631deba7ab75573eea2ccc2baaab97afff9be139185d5276ddef067
 
08:47:55.673 [AWT-EventQueue-0] DEBUG o.m.v.s.a.ImportPrivateKeysSubmitAction - Found 2 keys to import.2 
08:47:55.676 [AWT-EventQueue-0] DEBUG o.m.v.s.a.ImportPrivateKeysSubmitAction - Importing private keys in background SwingWorker thread 
08:47:55.723 [bitcoinj user thread] DEBUG o.m.c.bitcoin.BitcoinController - Keys added : [pub:04558bcaded4ffba8e52cf74a93d039d8eaf68bf71be72fec8f925919b18f4746be9a5a1e38b39b874e458be0c60327a0d737c2bb13d2e7f31cfeb9b6997095d0c encrypted] 
08:47:55.730 [SwingWorker-pool-4-thread-3] DEBUG o.m.v.s.a.ImportPrivateKeysSubmitAction - Wallet containing 0.00000001 BTC in:
  1 unspent transactions
  0 spent transactions
  0 pending transactions
  0 dead transactions
Last seen best block: (272580) 00000000000000048987a92b58aca7136a0a50358dee59a5ceebb1e9a41d04aa
Encryption: Scrypt/AES
========================================================

Why the addr "16Ng8gbbUnpxYffxRn27NEorUS6Ezzj6vv" changed to "19KniQUzkLvfKLFa6Ha3KPUKr16ZGY96tK" and missing?

**Comment by gary-rowe** [comment]
Key importing was improved in later versions. This is probably no longer relevant. Closing.
