### ISSUE TITLE
Copying of receive address to clipboard is imperfect

### ISSUE THREAD

**Issue by mackler** [jim618/multibit#544]
I just installed 0.5.17 onto Linux Mint Debian Edition 7.4.

When I select and copy a receive address from the "Request" page, it behaves oddly, unlike other applications that copy content to the clipboard, namely (1) it clears the existing clipboard content, but (2) not all applications recognize the content.  In particular, the Gnome terminal application, which has a paste feature, behaves as if the clipboard were empty, namely the paste menu option is grayed out, and Ctl-V pastes nothing.  On the other hand I can paste it into gedit, select and copy it from that application, and after that the terminal will see the clipboard contents.

This happens whether I copy in Multibit using Ctl-C or the copy button.  So far Gnome terminal is the only application that I see is not recognizing the clipboard content, but I just noticed this a minute ago.  I've never noticed any other application with a "copy-to-clipboard" action behaving in this way, in other words the Gnome terminal always recognizes clipboard content that other applications recognize.

**Comment by gary-rowe** [comment]
I doubt we'll be addressing Clipboard issues in MultiBit Classic, but extensive work has been done on this in MultiBit HD so I'll close this here.
