### ISSUE TITLE
Payment URL query `label` used, `message` ignored

### ISSUE THREAD

**Issue by mackler** [jim618/multibit#546]
I see on the `Send` tab there's a text-area for `Label` but no `message`, as specified in [BIP 21](https://github.com/bitcoin/bips/blob/master/bip-0021.mediawiki#Specification).

Also, the `Label` textarea looks to be multi-lined, but doesn't wrap [as davnd pointed out](https://github.com/jim618/multibit/issues/99).

If I'm reading BIP-21 correctly, the label is to identify the recipient, so it seems it should be a single line, meaning not-wrapping is correct, but the text-area in which it is displayed should appear as one line.  (Or rather, I don't see why it's a text area, since I'm not aware of why the user would need to edit it; perhaps it is saved somewhere--I'm new to Multibit.)

However, the `message` key is for a "message that describes the transaction to the user."  So I guess this is a feature request: add to the `Send` tab a line-wrapping text-area that displays the message.

To my way of thinking, being able to see the `message` is probably more important than seeing the `label`, since the user ought to know who the recipient is, but there is a greater risk of an error in *what* the user is paying for, for example the wrong product.  The merchant may have provided, for example, an invoice in the URL message field, but still the user will not see it (though he may see the name of the merchant in the `Label` area).

**Comment by gary-rowe** [comment]
Closing due to continued activity in MultiBit HD instead.
