### ISSUE TITLE
.desktop file for linux

### ISSUE THREAD

**Issue by drizzt** [jim618/multibit#551]
Hi,
what do you think about creating a multibit.desktop and a multibit script for correct linux installation?

The multibit script should contain something like:
```
#!/bin/sh
exec "$JAVA_HOME/bin/java" -jar /usr/share/java/multibit/multibit-exe.jar "$@"
```
And the multibit.desktop should contain something like:
```
[Desktop Entry]
Encoding=UTF-8
Type=Application
Name=Multibit
Comment=A lightweight Bitcoin desktop client powered by the BitCoinJ library.
Exec=multibit
Icon=multibit
Terminal=false
StartupNotify=false
Categories=Application;
```

**Comment by gary-rowe** [comment]
The [Linux installation guide](https://multibit.org/en/help/hd0.1/how-to-install-linux.html) shows how to build a suitable `.desktop` file for MultiBit HD. Closing.
