### ISSUE TITLE
Multibit install on Linux

### ISSUE THREAD

**Issue by jaquesaulait** [jim618/multibit#555]
Hi everyone, Ive been trying to install Multibit on Ub12.04 with no joy.  The incredibly useful instruction provided on their site, "Open a terminal window and make the installer executable with: chmod +x multibit-0.5.18-linux.jar" is staggeringly inadequate.  I've tried running this command in every folder in the Multibit folder, all I get is, "cannot access `multibit-0.5.18-linux.jar': No such file or directory"  Sure enough, searching for this file in the (entire) folder finds nothing.  I've installed Java.  I would really appreciate some help if someone out there can guide me, please!  Many thanks.  Jack, Devon.

**Comment by sandrokensan** [comment]
It is simple to launch jar files. Google is your friend.

**Comment by jaquesaulait** [comment]
yeah, really useful comment, sandro, thanks for FA.  And Google is a spy.

**Comment by sandrokensan** [comment]
Use Other Search engines. Google (I don't use google) has a lot of info about linux and jar file.

In my opinion this is question for google and not for github.

**Comment by gary-rowe** [comment]
MultiBit HD provides an easier installation experience and improved installation instructions.

Closing.
