### ISSUE TITLE
How do I make bitcoin links clickable?

### ISSUE THREAD

**Issue by Mikaela** [jim618/multibit#573]
I have understood that bitcoin links should be clickable in browser and clicking them opens multibit.

This doesn't appear to be the default behaviour and I have tried creating a .desktop file and registering it with xdg-open without results with [these instructions](http://mtotschn.blogspot.fi/2013/11/open-bitcoin-urls-in-firefox-with.html) and Google Chrome only opens a new Google Chrome window when I click bitcoin links.

**Comment by gary-rowe** [comment]
There are [additional instructions on the website](https://multibit.org/en/help/hd0.1/how-to-install-linux.html) covering this issue. Closing since they should resolve the problem.
