### ISSUE TITLE
Determine wallet password with older unencrypted wallet file

### ISSUE THREAD

**Issue by vamosrafa** [jim618/multibit#603]
So I have a backup of my unencrypted wallet file. I can't find my password for my encrypted wallet file, the encrypted file has a new address missing from the encrypted file. Is there any way to gain access to the new encrypted address. I sent a good amount of coin to the now locked encrypted address.

Multibit is great software, this was obviously my fault. However there was some language on the website that lead me to believe all might not be lost.

**Comment by gary-rowe** [comment]
Apologies for the slow response to this. Your only hope of recovering that wallet is to recover the password. This article contains more detail: https://multibit.org/en/help/v0.5/help_lostOrForgottenPassword.html.

Unfortunately, there's nothing else we can do.

Closing.

**Comment by pattersonn** [comment]
@vamosrafa 
did you recover your multibit wallet,
this is the issue which occurs a lot for older versions of multibit, I can recover your wallet if you still have this problem contact me at : walletsrecoveryservice@gmail.com
