### ISSUE TITLE
Transaction never went through and my balance is incorrect

### ISSUE THREAD

**Issue by hyhycaptaincoins** [jim618/multibit#604]
I transferred money to a receiving address in the same wallet as the sending address.  This was a total accident.  However, all of my BTC is gone.  How do I get this back?

Here is the blockchain info: https://blockchain.info/tx-index/ffb82307a580ac7f9a6deb1348e48c689a6914a39ee1b0a3817058615ef3e369

**Comment by gary-rowe** [comment]
Apologies for the slow response. This kind of situation requires that you contact the owner of the address and hope that they issue you with a refund.

Unfortunately, there's nothing else we can do.

Closing.
