### ISSUE TITLE
Multibit paying out but no verifying

### ISSUE THREAD

**Issue by rodeoguy909** [jim618/multibit#614]
I am getting my normal payouts but none will verify for the past week? Is there anything I can do?

**Comment by gary-rowe** [comment]
Apologies for the slow response.

Can you confirm you have read this article: https://multibit.org/en/help/v0.5/help_support_sentBitcoinToMultibitButTheyNeverArrived.html

**Comment by rodeoguy909** [comment]
Thanks a bunch, I got it working


[Twitter]<https://twitter.com/ComtechNetworkS>[Facebook]<https://www.facebook.com/pages/ComTech-Network-Solutions/126453047418459>[Google+]<https://plus.google.com/106863293716358961586/about>[LinkedIn]<http://www.linkedin.com/company/comtech-network-solutions?trk=tyah&trkInfo=tarId:1405433673008,tas:comtech+network,idx:1-1-1>website<http://www.comtechnc.com/> |  map<https://www.google.com/maps/place/Comtech+Network+Solutions/@36.046343,-79.39535,17z/data=!3m1!4b1!4m2!3m1!1s0x88532ca424253439:0x146c109d39be342d> |  email<mailto:ethan@comtechnc.com>

[Ethan Farlow, ComTech Network Solutions, (336) 570-9409]


ComTech Network Solutions
1204 South Main Street | Graham, NC 27253
Main (336) 570-9409 | Fax (336) 570-9499
Direct (336) 494-1024


[cid:image010.gif@01D03C6A.868B7230]
