### ISSUE TITLE
Features List

### ISSUE THREAD

**Issue by aalsawafi** [jim618/multibit#616]
Dear all,

I'm working on a project requiring adding/implementing some new features to one of the cryptocurrency systems. So, i would be grateful if you can provide me the features (list) that have not yet implemented.

Many Thanks in advance,

**Comment by gary-rowe** [comment]
Apologies for the slow response. You can track all our features through GitHub's milestones feature.

HD: https://github.com/bitcoin-solutions/multibit-hd/milestones
Classic: https://github.com/jim618/multibit/milestones

Closing.
