### ISSUE TITLE
HELP Deleted MultiBit Wallet Had Several BTC Need Help Getting Stored Coin Data!

### ISSUE THREAD

**Issue by MeedMultiBitHelp** [jim618/multibit#625]
Bug report
  Operating System: 0.5.18 Windows XP
  MultiBit Version: 0.5.18
  Steps to replicate the problem: Received BTC from peer, once the BTC was received on MultiBit Wallet, cord for power to computer was disconnected. Laptop has non-working battery, so computer shut down. When computer strated back up, it started in safe mode, and did a system restore, when sytem logged back on to computer, the recently installed multibit software was not there, when computer does system restore in safe mode, it can not save new programs, it restored computer to a point before multibit was saved, so I can not find my wallet, back up, or anything involving several amounts of btc, please help figure this out, I losy multibit wallet with lots of btc and now im broke, is there stored coin data, this link is my blockchain info, I have th wallet address to I need someones help to find my deleted wallet and I will share btc with person, please help!

https://blockchain.info/address/13jwSYSA3uKf84DF47CrPpAGk3QvrxfS77

**Comment by steauacris89** [comment]
I want Multibit owner to give back btc to all members who have problems . are 850 $ i this fake error and all of this are money from multibit members. I want him to answer me and give a solution . 
Multibit error take my btc , i want my btc back .
I want btc owner to respond my message and give a solution.
I will post any every forum about this bug and how btc owners dont want to resolve it .
