### ISSUE TITLE
Incomplete webpage

### ISSUE THREAD

**Issue by Elendilll** [jim618/multibit#627]
Hi,

Can you add to your page: MultiBit V0.5.10, because this folder:
https://multibit.org/releases/multibit-0.5.10/
is empty and I don't know why.

**Comment by steauacris89** [comment]
I want Multibit owner to give back btc to all members who have problems . are 850 $ i this fake error and all of this are money from multibit members. I want him to answer me and give a solution . 
Multibit error take my btc , i want my btc back .
I want btc owner to respond my message and give a solution.
I will post any every forum about this bug and how btc owners dont want to resolve it .
