### ISSUE TITLE
Feature Request: JSON-RPC Interface

### ISSUE THREAD

**Issue by PierreRochard** [jim618/multibit#629]
Hi,

An API that allows me to pull the same information as a CSV export would be great! Let me know if this is possible / in the works.

Thanks,

PIerre

**Comment by gary-rowe** [comment]
Apologies for the slow response. This is very unlikely to be implemented in Classic and is not on our roadmap for MultBit HD. The vast majority of our users would have no use for it and we're trying to keep the wallet as simple as possible.

Closing.
