### ISSUE TITLE
Readme requires building bitcoinj fork which does not compile until after multibit

### ISSUE THREAD

**Issue by adamlsmith** [jim618/multibit#630]
When building the fork, I get:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:testCompile (default-testCompile) on project bitcoinj: Compilation failure: Compilation failure:
[ERROR] /home/adam/workspace/jimburton618-bitcoinj-coinbase-tx/core/src/test/java/com/google/bitcoin/core/TestUtils.java:[94,32] createFakeTx(com.google.bitcoin.core.NetworkParameters,java.math.BigInteger,com.google.bitcoin.core.Address,com.google.bitcoin.core.Address) is already defined in com.google.bitcoin.core.TestUtils
[ERROR] /home/adam/workspace/jimburton618-bitcoinj-coinbase-tx/core/src/test/java/com/google/bitcoin/core/CoinBaseBlockTest.java:[28,37] package org.bouncycastle.util.encoders does not exist
[ERROR] /home/adam/workspace/jimburton618-bitcoinj-coinbase-tx/core/src/test/java/com/google/bitcoin/core/CoinBaseBlockTest.java:[60,40] cannot find symbol
[ERROR] symbol  : variable Hex
[ERROR] location: class com.google.bitcoin.core.CoinBaseBlockTest

However if I then mvn clean install the primary (multibit) repo, then the above fork compiles fine afterwards.

**Comment by steauacris89** [comment]
I want Multibit owner to give back btc to all members who have problems . are 850 $ i this fake error and all of this are money from multibit members. I want him to answer me and give a solution . 
Multibit error take my btc , i want my btc back .
I want btc owner to respond my message and give a solution.
I will post any every forum about this bug and how btc owners dont want to resolve it .

**Comment by gary-rowe** [comment]
Apologies for the slow response. I can't replicate this locally when I build MultiBit Classic.

Closing since this is quite old and possibly no longer relevant.
