### ISSUE TITLE
Wallet sync extremely slow and transactions need to be consolidated

### ISSUE THREAD

**Issue by wupenghua** [jim618/multibit#635]
I have encountered problem with MultiBit-0.5.18. My MultiBit wallet never sync correctly. I have tried to move my wallet to different laptops under the guide of https://multibit.org/en/help/v0.5/help_movingAWallet.html. It is extremely slow no matter which computer I use and no matter which location I try. Currently I use a DELL server to do the sync. The OS on that DELL server is Windows 2008 Server. It is extremely slow too. At current speed, It may take 1-2 months to get 100% transaction synced. I have nearly 600 transactions since last November. I have checked previous case posted on GitHub and none of them fits my case.
Of course, I can't send BTC from my MultiBit wallet. Then, I got my private key exported from the MultiBit wallet. I imported that key to my BlockChain wallet. However, my BlockChain wallet fails to load the transaction balance after import. I have checked the imported wallet address and I found "This wallet contains a very large number of unspent outputs. Please consolidate some outputs". I don't know how to "consolidate some outputs".
BTW, I am keeping my MultiBit wallet opened to sync my transaction after BlockChain wallet import. I suppose it's OK to have two wallet program downloading data from the same address as long as I don't send&receive from this address. Am I correct?

**Comment by steauacris89** [comment]
I want Multibit owner to give back btc to all members who have problems . are 850 $ i this fake error and all of this are money from multibit members. I want him to answer me and give a solution . 
Multibit error take my btc , i want my btc back .
I want btc owner to respond my message and give a solution.
I will post any every forum about this bug and how btc owners dont want to resolve it .
