### ISSUE TITLE
Coins still not appearing in wallet after several days??

### ISSUE THREAD

**Issue by wormlandworm** [jim618/multibit#636]
A transfer occurred on the 14/11/2014 and it has been confirmed on blockchain that the transaction was successful with over 398 confirmations and marked as CONFIRMED however nothing is appearing in the multibit wallet. 

Running the latest version, have closed and re-opened wallet, previously it was working fine with other wallets. Please assist with this issue asap.

**Comment by steauacris89** [comment]
I want Multibit owner to give back btc to all members who have problems . are 850 $ i this fake error and all of this are money from multibit members. I want him to answer me and give a solution . 
Multibit error take my btc , i want my btc back .
I want btc owner to respond my message and give a solution.
I will post any every forum about this bug and how btc owners dont want to resolve it .
