### ISSUE TITLE
Wallet without extension issues

### ISSUE THREAD

**Issue by StormeNet** [jim618/multibit#643]
#### Multibit doesn't close after loading wallet without extension (also doens't show up untill restart of Multibit)
  Operating System: Windows 7
  MultiBit Version: 0.5.18

  Steps to replicate the problem:
* Create Wallet
* Unload wallet
* remove .wallet from extension
* Load wallet (doesn't show up in Multibit)
* try to close multibit
* After Multibit is killed restart multibit
* Wallet appears but still can't close Multibit

**Comment by steauacris89** [comment]
I want Multibit owner to give back btc to all members who have problems . are 850 $ i this fake error and all of this are money from multibit members. I want him to answer me and give a solution . 
Multibit error take my btc , i want my btc back .
I want btc owner to respond my message and give a solution.
I will post any every forum about this bug and how btc owners dont want to resolve it .

**Comment by gary-rowe** [comment]
Fiddling about with critical operational files is not recommended. You'll see all kinds of strange behaviour and put your bitcoins at risk.

Closing.
