### ISSUE TITLE
MultiBit 0.5.18 - Bitcoins recieved in Multibit and sent to another address - Bitcoins now missing

### ISSUE THREAD

**Issue by Jandt14** [jim618/multibit#647]
Im using MultiBit 0.5.18. Bitcoins were received in my wallet. I sent them on to another address for payment of goods. Bitcoins are now missing from my MultiBit wallet (received transaction still visible) the sent transaction is not appearing and the amount sent is no longer on the transactions list even though the Bitcoins are no longer there. The receiving address has not received them. I have tried resetting the blockchain and transactions and this has not fixed the problem. What do I do?

**Comment by steauacris89** [comment]
I want Multibit owner to give back btc to all members who have problems . are 850 $ i this fake error and all of this are money from multibit members. I want him to answer me and give a solution . 
Multibit error take my btc , i want my btc back .
I want btc owner to respond my message and give a solution.
I will post any every forum about this bug and how btc owners dont want to resolve it .

**Comment by steauacris89** [comment]
Why you closed this topic Mr Gary .

More and more people have big problems with Multibit and you have not done nothing .

You remember me , 3 years ago Multibit eat my BTC ( APROX 1 BTC ) and noone gived me an explication .

İ know who are you and trust me , i have not forget what you and your friend done .

You have any solution for my problem or i need to take other actions ??

Thank you
