### ISSUE TITLE
Bit coins missing

### ISSUE THREAD

**Issue by 0192837465** [jim618/multibit#648]
Bug report
I have sent bit coins to an address and it was only seen by one peer. I now cant see the transaction to see block chain or know where it is.
  Operating System:Mac OS X 
  MultiBit Version:0.5.16
  Steps to replicate the problem:
Restarted and reset block chain. The transaction details have now completely disappeared and i dont have the bit coins in my account.

**Comment by steauacris89** [comment]
I want Multibit owner to give back btc to all members who have problems . are 850 $ i this fake error and all of this are money from multibit members. I want him to answer me and give a solution . 
Multibit error take my btc , i want my btc back .
I want btc owner to respond my message and give a solution.
I will post any every forum about this bug and how btc owners dont want to resolve it .
