### ISSUE TITLE
Wallet lost due a failer HDD ( curupted wallet )

### ISSUE THREAD

**Issue by calhounchad** [jim618/multibit#649]
few days ago my HDD just stop working and I lose all my bitcoins. After 3 days I just recover the wallet file from hdd but is corrupted. All time when i try to open I get : error null. Please let me know if there any way to get my coins back. Thank

**Comment by steauacris89** [comment]
I want Multibit owner to give back btc to all members who have problems . are 850 $ i this fake error and all of this are money from multibit members. I want him to answer me and give a solution . 
Multibit error take my btc , i want my btc back .
I want btc owner to respond my message and give a solution.
I will post any every forum about this bug and how btc owners dont want to resolve it .
