### ISSUE TITLE
Synchronisation blocks at 60%

### ISSUE THREAD

**Issue by Kopplex** [jim618/multibit#657]
Operating System: Win 7
 MultiBit Version: 0.5.18
Steps to replicate the problem: 
Hi i am meeting a strange probleme, when i open multibit the synchronisation don't go to the send, she always blocks at 60%, i need to fix this probleme because i have bitcoin in my wallet i dont want to loose them, thx 
screen : http://www.hostingpics.net/viewer.php?id=297114MultibitBeug.jpg

**Comment by bitcoin-solutions** [comment]
We've seen this sometimes when a user has accidentally set the wrong date on their computer (for whatever reason). Then MultiBit will only sync to the computer's date.  Have a check of that.

**Comment by steauacris89** [comment]
I want Multibit owner to give back btc to all members who have problems . are 850 $ i this fake error and all of this are money from multibit members. I want him to answer me and give a solution . 
Multibit error take my btc , i want my btc back .
I want btc owner to respond my message and give a solution.
I will post any every forum about this bug and how btc owners dont want to resolve it .
