### ISSUE TITLE
How do I set this up?

### ISSUE THREAD

**Issue by dlc1962** [jim618/multibit#658]
My wallet is bitcoin but I can't figure out how to set it up with multibit. Can someone help me out?

**Comment by dlc1962** [comment]
I meant blockchain

**Comment by gary-rowe** [comment]
Can you verify that you've read this article: https://multibit.org/en/help/v0.5/help_movingAWallet.html?

**Comment by dlc1962** [comment]
I read it but I'm still confused as to how to export the key to blockchain.
I'm not tech minded so could explain as to what files I open to find the
password protected key, etc?

**Comment by bitcoin-solutions** [comment]
Hi,
Whilst it is possible to move private keys around between blockchain and MultiBit we only advise doing it to recover funds otherwise unavailable. It is a LOT simpler and safer to move funds between wallets simply by spending from one to the other.

**Comment by dlc1962** [comment]
I'm new to all this so how would I do that? What do I do to get multibit to
start making bitcoins?

**Comment by gary-rowe** [comment]
Think of MultiBit has a completely separate wallet to the one at Blockchain.info. It does not do any mining (create bitcoins), it simply holds the private keys to your existing bitcoins securely.

You can send and receive bitcoins by using the appropriate tabs. 

Have a read of https://multibit.org/en/help/v0.5/help_receivingBitcoin.html and use the address provided there as the receiving address for any funds you wish to send to it from your Blockchain.info wallet.

**Comment by dlc1962** [comment]
I guess I'm missing something because I see how in blockchain how I add any
money so it'll start mining.

**Comment by gary-rowe** [comment]
You're confusing the mining process (creating blocks) with transactions (putting transactions into blocks).

Here is a handy FAQ about how Bitcoin works that may help: https://multibit.org/faq.html

**Comment by dlc1962** [comment]
I'm still a little confused. How much would be the lowest amount I could
put in my wallet so I could start making bitcoins? And from what sources?

**Comment by bitcoin-solutions** [comment]
Hi dic1962,

Glad you are enjoying discovering bitcoin - it's fascinating once you get into it.

This is an issues database for when people find bugs etc in MultiBit so isn't really a discussion forum.
You'll probably need to watch a few videos and read a few articles before the pieces come together.
(For instance - you can't mine using MultiBit or any other desktop wallet now).

bitcoin.org is a good place to start for more info.

**Comment by dlc1962** [comment]
I still would I finance account at blockchain so I can start making
bitcoins.

**Comment by gary-rowe** [comment]
You definitely need to do a lot more reading around how Bitcoin works. Bear in mind that bitcoins in normal wallets do not accrue interest nor is it realistic for a person to enter the mining business without a lot of extremely expensive equipment (100,000 USD entry level). 

You can find many jump off links here: https://multibit.org/community.html

Since this is no longer a MultiBit support issue, I'll close this ticket now.
