### ISSUE TITLE
While Importing Keys, Multibit goes from "Online" to "connecting..." after a few minutes.

### ISSUE THREAD

**Issue by impressivegol** [jim618/multibit#659]
I am trying to import a large number of keys, and it seems like everything is fine initially. The standard lag at the beginning takes place, and then it goes to "Importing...".   I notice though that after a few minutes, on the bottom left hand corner where Multibit usually says ONLINE in green, it switches to CONNECTING (in red letters). and then multibit just freezes from there, and I'm forced to Quit and abandon the task or it stays on the same screen.  I even allowed hours pass before quitting lol

anyone have any idea why this is happening? I am under a very solid network connection.  Is it because the keys file may be a large one?  any help would be appreciated, thanks in advance.

**Comment by gary-rowe** [comment]
Can you provide some details of the number of keys involved? If it's 1000+ then it is probably worth breaking the import up into separate groups.

**Comment by impressivegol** [comment]
thanks for the reply Gary, it is a few thousand.  I was thinking of breaking it up into separate groups but was unsure of how to exactly do that

**Comment by gary-rowe** [comment]
Here's some technical information on the file format that should help: https://multibit.org/en/help/v0.5/help_exportingPrivateKeys.html

**Comment by impressivegol** [comment]
thank you but shouldn't I be importing and not exporting?

**Comment by gary-rowe** [comment]
The export format is shown there, but you use the same format for importing. Bear in mind that manual importing of private keys is fraught with hazard, if you're in a position to simply use the Bitcoin network to spend the coins to a suitable destination then archive the private keys in case of reuse then you should use that approach instead.

You may find this MultiBit HD (beta) article helpful: https://beta.multibit.org/en/help/hd0.1/how-to-upgrade-from-classic.html

**Comment by impressivegol** [comment]
thanks i guess im better off dong that and with less hassle.

**Comment by steauacris89** [comment]
I want Multibit owner to give back btc to all members who have problems . are 850 $ i this fake error and all of this are money from multibit members. I want him to answer me and give a solution . 
Multibit error take my btc , i want my btc back .
I want btc owner to respond my message and give a solution.
I will post any every forum about this bug and how btc owners dont want to resolve it .
