### ISSUE TITLE
sent bitcoin from coinbase. not appearing

### ISSUE THREAD

**Issue by jihaddakkak** [jim618/multibit#662]
Bug report
  Operating System: Windows 7
  MultiBit Version: 0.5.18
  Steps to replicate the problem: I sent my bitcoins from coinbase to multibit. Coinbase states that the process is complete. The funds have not appeared. I followed the troubleshooting section and reset the blockchain multiple times. I pasted the transaction detail below. I directly copied and pasted the address from multibit, however it doesn't match the address that is currently showing on multibit.
please help.

377df3bbf2d3590078ed6a65b194e6a84e5e821d39e36924436f2b6abffe0e68
Index / CBInputs    w/ sigs
1APVVKGFxTRpmGLF9JmW5vDmdE4KJa3GZQ
0 / No
12KufuuT3Nt5zkFK8WMBKfWy15tGPAQeqJ
1 / No
    0.23327896
conf
    0.00150771
conf
Outputs    w/ pub keys
1ADfdTWZVnsUdLUVRWSvUTotc6JWy7Nb9w
14ZQ22Gvrqr7gnYyiEU1w2WkgSv4aycBEs

    0.23327896    spent 
    0.00140771    

Transaction details
Hash	377df3bbf2d3590078ed6a65b194e6a84e5e821d39e36924436f2b6abffe0e68
In Block	00000000000000000f2e7b3882f50beea79a3c7331ab5282b61abd3928cd1701
Confirmations	5
Multisig	No
First seen	January 26, 2015 08:05 (about 1 hour ago)
Version	1
Lock Time	0
Size	438 Bytes
Pool	tx pool
Fee	0.0001 BTC
Formats	binary | json

**Comment by gary-rowe** [comment]
Can you verify that you used an address from the "Receive" tab. Sometimes people have been known to use ones from the "Send" tab and end up having to contact third-parties for a refund.

**Comment by jihaddakkak** [comment]
I see the address now. I did copy the one in the send tab. What do I do? I'm a total noob

**Comment by gary-rowe** [comment]
Unfortunately there is no technical fix for this. You will need to identify the owner of the address and contact them directly and explain the situation. Since it is likely that you sent them bitcoin at some point in the past you have a chance of getting it resolved in your favour. 

I'll close this issue now since it falls outside of MultiBit support.
