### ISSUE TITLE
Please enable DMARC on your multibit.org domain

### ISSUE THREAD

**Issue by agustinf** [jim618/multibit#663]
I know this might not be the best place to put this, but I just wanted to let you know that DMARC can help you avoid phishing scams with your domain. 
The steps you should follow are:
1. Enable DKIM and SPF
2. Add a _dmarc.multibit.org TXT DNS value that reports to you and check which emails would pass
3. Enable strict rejection of emails that don't pass DMARC evaluation.
 Learn more here: http://dmarc.org/

**Comment by gary-rowe** [comment]
Thanks for letting us know. I've replicated this issue on the website repo which is more appropriate for this kind of issue so I'll close it here.
