### ISSUE TITLE
[Minor bug] Losing connection to Trezor after cancelling 'Change Pin' action

### ISSUE THREAD

**Issue by lkamp** [jim618/multibit#669]
I just played around with Multibit and my Trezor (which by the way is the best combination for me right now!) and stumbled about the following behavior (a Trezor has to be connected):

1.) Go to "Manage Wallet", click "Change Pin".
2.) Select "Change an existing PIN or add a new PIN" and click "Next".
3.) A message appears on the Trezor asking if you want to change the PIN of the device.
4.) When you press the "Cancel" button on the Trezor, Multibit tells you it discovered a new Trezor.

Sometimes, after clicking "Yes" to use your Trezor, the Trezor gets re-initialized, sometimes it doesn't and you can use the wallet. I've tagged the issue with "Minor Bug" because the wallet continues to work with the Trezor, however I think it should not tell me about a new Trezor when I cancel an action on the device.

**Comment by gary-rowe** [comment]
This is the MultiBit Classic issue database. I've moved your issue to [Multibit HD #443](https://github.com/bitcoin-solutions/multibit-hd/issues/443) and closed this one to avoid confusion.
