### ISSUE TITLE
Open Bitcoin Privacy Protect Privacy Questionnaire for MultiBit

### ISSUE THREAD

**Issue by kristovatlas** [jim618/multibit#671]
Greetings MultiBit contributors,

The Open Bitcoin Privacy Project is conducting a survey of the privacy features in Bitcoin wallets as part of an ongoing measurement effort. As part of the project, we’ve selected MultiBit's wallet for inclusion into the survey. Mostly I've been emailing companies to get tehse questions answered, but couldn't find any point of contact for MultiBit other than Git issues; I hope this is an acceptable venue to request answers for the questionnaire.

Several of the and behaviors we track are difficult to discern from outside observation, and that’s why we’re requesting your help to answer a few questions about your application’s features. We greatly appreciate your help with this survey, and will include all information you provide below in the final published report.

1. Please classify your application as one of the three categories:

    a. Wallet: all of the private keys needed to create a blockchain transaction are under the exclusive control of the user

    b. Pseudo-wallet: none of the private keys needed to create a blockchain transaction are under the exclusive control of the user

    c. Hybrid wallet: some portion of the private keys needed to create a blockchain transaction are under the exclusive control of the user

2. Does your application provide any type of visual warning to the user when events which may reduce their privacy or safety occur, such as:

    a. Receiving funds to an address which has previously received incoming transactions

    b. Backups have been invalidated by new receiving or change address creation

    c. If the wallet supports mixing, a proposed mixing transaction is easily reversible

    d. An outgoing transaction sends funds to a previously-used address

    e. An outgoing transaction links inputs from multiple addresses

    f. Network connectivity to peers or dedicated balance servers is not routed through an anonymous channel

    g. An outgoing transaction links inputs from multiple accounts/identities

3. Does your application’s backup process involve any activity which may be visible to an external network observer?

4. Does your application take positive steps to make change outputs indistinguishable from spending outputs, such as:

    a. Randomizing the number of change outputs

    b. Randomizing the position of the change output(s)

    c. Selecting sufficient input value such that the change output(s) closely resemble the size of the desired spend

    d. Intentionally creating “decoy” change outputs that have a low number of significant digits

5. If your application includes mixing functionality:

    a. Is it possible for a malicious participant in the mix to steal funds?

    b. Is it possible for any participant in the mix to retain information which correlates outputs to their corresponding inputs?

6. If your application obtains balance information from dedicated servers:

    a. Is it possible to operate the dedicated servers in a manner which correlates:

        i. A user’s receiving or change address to another receiving or change address in the same wallet

        ii. Any of the above with a public IP address

        iii. Any of the above with a registered account

        iv. Any of the above with a persistent software or hardware fingerprint

7. If your application obtains balance information by uploading a filter to network peers:

    a. Are filters ever updated in a manner that allows the peer to correlate the old and new filter with the same connection?

8. Does your application take positive steps to route outgoing transactions through different path to the network than the path via which it receives balance and incoming transaction information?

9. If your application supports multiple accounts/identities:

    a. Does your application take positive steps to route balance, incoming and outgoing transaction information through different network paths for each account/identity?

Thank you for assisting us with this effort to measure privacy progress in the Bitcoin wallet space.  If at all possible, please return this survey before 2015-03-16 to ensure the Q1 rating for your application will be as accurate as possible.

Please feel free to reach out with any questions or concerns you may have.

Thank you,
Kristov Atlas
Open Bitcoin Privacy Project

**Comment by jim618** [comment]
Hi Kristov,
Thanks for your issue - I am one of the co-developers so can answer your query.
Note that we also have an HD wallet in beta which addresses a number of address reuse issues - have a look at https://beta.multibit.org

This reply is specifically to the extant MultiBit Classic being offered currently on https://multibit.org

1a. All private keys are under exclusive control of the user.
2. No
3. No - backups are performed by the user.
4. No.
5. There is no mixing in MultiBit Classic
6. MultiBit Classic does not obtain balance info from other servers. It gets (bloom-filtered) tx information from Bitcoin Core nodes.
7. The bloom filters used by MultiBit (and other bitcoinj based wallets) are susceptible to reverse engineering if an attacker can monitor all the user's network traffic unfortunately.
8. It broadcasts on one Bitcoin Core node and listens on others yes.
9. MultiBit Classic does not support multiple identities.

Regards,

Jim

**Comment by kristovatlas** [comment]
Hey Jim, thanks so much for taking the time to respond to our survey. I've incorporated the information into our evaluation of Multibit Classic for 2015 Q1. Looking forward to the release of the HD wallet!
