### ISSUE TITLE
Can't click on menus

### ISSUE THREAD

**Issue by a442** [jim618/multibit#672]
I can't click any of the items in the "File" and other menus. A .gif showing the issue follows.

http://i.imgur.com/PeBOE1Q.gif

I have downloaded the Linux installer from multibit's website. I have installed it following the instructions on the same website. The installation seems to have been successful. I ran multibit with `java -jar multibit-exe.jar`. The output was:

20:31:51.373 [main] INFO  o.m.ApplicationDataDirectoryLocator - Application data directory.1 = '/home/debian/MultiBit' 

I am on Debian Jessie.

java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-2)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)

I am using xmonad 0.11

Multibit log file: http://pastebin.com/AB68pwh3

**Comment by jim618** [comment]
Thanks for your feedback.
It looks like it is something to do with the interaction of our Java app and the windows manager (xmonad) as it is the latter that 'owns' the menus.

I cannot think of an obvious way to fix it so I suggest you don't put any money into that wallet. 
(If you have then the wallet file is the same across all OS so you can copy it to another OS no problem).

**Comment by a442** [comment]
I can confirm the issue is with the window manager, as it works with xfce's one. I'll write the xmonad devs instead. Thanks.

**Comment by gary-rowe** [comment]
Seems to be resolved. Closing.
