### ISSUE TITLE
Confirmation issues on Multibit

### ISSUE THREAD

**Issue by bartolo94** [jim618/multibit#674]
I sent some btw (3 transaction) but after 1 month i received 0 confirmation, on blockchain the transaction doesn't exist and on the other wallet they didn't receive anything yet! 
How can i do?

**Comment by jim618** [comment]
If the tx does not appear on blockchain.info or at the recipient then almost certainly it was never sent and hence your bitcoins are still spendable.
Have a read of this support article for steps you can take:
https://multibit.org/en/help/v0.5/help_support_sentBitcoinToMultibitButTheyNeverArrived.html
