### ISSUE TITLE
Multibit send failure triangle status

### ISSUE THREAD

**Issue by acecafe** [jim618/multibit#675]
I created a new wallet and sent alot of BTC from another wallet to the newly created one.  In the sending wallet the transaction shows a triangle status.  I restarted multibit, reset the blockchain.  Let the app run for about 24 hours and nothing I do seems to recover the transaction.  Somebody please help.  I now have a zero balance in the sending wallet and a zero balance in the receiving wallet.

**Comment by acecafe** [comment]
How do I reset the block chain to the day before the transaction was sent?  I don't have an option to pick a date

**Comment by acecafe** [comment]
I reset the blockchain and transactions a couple more times and now I don't see the big transaction out and the balance is wrong

**Comment by jim618** [comment]
If the transaction did not transmit ok from your first wallet (the triangle status) then the transaction never made it ok to the Bitcoin network. There is more info in the help here:
https://multibit.org/en/help/v0.5/help_support_sentBitcoinToMultibitButTheyNeverArrived.html
and 
https://multibit.org/en/help/v0.5/help_support_sentBitcoinFromMultibitButTheyAreStuck.html

Thus your bitcoin are under control of your first wallet and that is the one that needs reseting.
You cannot choose a date when doing a reset.

If none of that works then your best avenue is to export your private keys and import them into something like block chain.info. There is a how to in the help here:

https://multibit.org/en/help/v0.5/help_movingAWallet.html
