### ISSUE TITLE
I lost bitcoin, please help me

### ISSUE THREAD

**Issue by rendra99** [jim618/multibit#679]
Bug report
  Operating System: win 7 32bit
  MultiBit Version: 0.5.18
  Steps to replicate the problem: I had just closed my wallet, but bitcoin I immediately go away and I also do not know if it will happen like that, please help me restore my wallet, all the way I have tried, only the treasure of my bitcoin
This wallet was missing my bitcoin
1BTgaL12v7tWwRnoRxDVUQuyudFBH8UCxE

**Comment by jim618** [comment]
Have a read of the support note:
https://multibit.org/en/help/v0.5/help_support_missingWallets.html

**Comment by rendra99** [comment]
the word ".wallet" was not found, please help me

**Comment by rendra99** [comment]
hat there is only backup my wallet which had just created a new, and the old has gone before does not appear his wallet backup
please help me this is my bitcoin wallet missing
1BTgaL12v7tWwRnoRxDVUQuyudFBH8UCxE

**Comment by scotty41** [comment]
Apple OSX 10.10.2
Multibit 0.5.18
Have done everything suggested in the help section, no luck at all.  


I am in exactly the same position.  One minute they were there and then they disappeared.  
I took this from the error log, perhaps this may be of some use in assisting the individual who opened the thread and myself.  this is a small sample of the WARNINGS.  It goes on and on this.  I only can 

22:16:08.221 [NioClientManager] WARN  c.g.bitcoin.core.AbstractBlockChain - Saw duplicated block in main chain at height 298442: 000000000000000073da8dcc0fffdd663e8d021a71c42d68ce2703072bba8aab 
22:16:08.222 [NioClientManager] WARN  c.g.bitcoin.core.AbstractBlockChain - Saw duplicated block in main chain at height 298443: 00000000000000002b6043dd8f57164a4bad2c490112f671dda4b79943378e8b 
22:16:08.223 [NioClientManager] WARN  c.g.bitcoin.core.AbstractBlockChain - Saw duplicated block in main chain at height 298444: 000000000000000088734d90708752e4e785ef34533de72149e0fd3031d24be5 
22:16:08.224 [NioClientManager] WARN  c.g.bitcoin.core.AbstractBlockChain - Saw duplicated block in main chain at height 298445: 000000000000000001732ffee213112cb51302e03be0a535cb7308126d2d3911 
22:16:08.225 [NioClientManager] WARN  c.g.bitcoin.core.AbstractBlockChain - Saw duplicated block in main chain at height 298446: 000000000000000026ee085580b472e73191bb7a1540c90cf303e6cac4607385 
22:16:08.226 [NioClientManager] WARN  c.g.bitcoin.core.AbstractBlockChain - Saw duplicated block in main chain at height 298447: 00000000000000007ea575924254d5ff79923a6ea950c159cd673e9905ab1d45 
22:16:08.227 [NioClientManager] WARN  c.g.bitcoin.core.AbstractBlockChain - Saw duplicated block in main chain at height 298448: 00000000000000007076e24da4d2bb0294c0068bc7472013f68e01644856028d 
22:16:08.229 [NioClientManager] WARN  c.g.bitcoin.core.AbstractBlockChain - Saw duplicated block in main chain at height 298449: 0000000000000000166b129bb61eeb5f8256502eb161dfb2ae013265ee44b3cb 
22:16:08.230 [NioClientManager] WARN  c.g.bitcoin.core.AbstractBlockChain - Saw duplicated block in main chain at height 298450: 00000000000000000bbe9a420d60684c70db1e2364f18a7c10834cff33c1a4fb 
22:16:08.231 [NioClientManager] WARN  c.g.bitcoin.core.AbstractBlockChain - Saw duplicated block in main chain at height 298451:

**Comment by rendra99** [comment]
I users windows 7 32bit
I report that my .wallet backups do not exist in all folders after I close
my wallet, and there bitcoin I needed, help to help track it down with my
bitcoin wallet address this
1BTgaL12v7tWwRnoRxDVUQuyudFBH8UCxE

**Comment by gary-rowe** [comment]
According to [blockchain.info](https://blockchain.info/address/1BTgaL12v7tWwRnoRxDVUQuyudFBH8UCxE) there is still a non-zero balance for that address so it is unlikely that they have been stolen. 

MultiBit will not delete a wallet so for there to be no `.wallet` files indicates that something else has deleted them.

One way to check this is to open a File Explorer window on to the MultiBit application directory (see the [Troubleshooting guide](https://multibit.org/en/help/v0.5/help_troubleshooting.html) for details). Then open MultiBit and use File | New to create a fresh wallet. You'll see it appear in the File Explorer Window. Use File | Exit to quit MultiBit and observe what happens to your new wallet in the File Explorer. 

If it gets deleted then there is a good chance you have malicious software running on your machine and you will need to get it removed as soon as possible. If not (much more likely) then you should attempt to use file recovery software to restore the missing wallets and backups. You may find this article helpful: http://gary-rowe.com/agilestack/2012/08/17/how-to-recover-your-bitcoins-from-a-failed-hard-drive/

**Comment by rendra99** [comment]
yes it is true that there is no pure steal because it belongs to me, my laptop for multibit very safe from the reach of the virus, so I'm please to blockchain.info to help restore my backup .wallet that do not exist in my laptop, I had no idea what to do let alone all the way I have done but the results are not there, the way one of them is asking for help to blockchaiin.info and backup .wallet multibit to find my missing after I shut my wallet 2 days ago, I beg all to you all.
thanks please reply later further information.

**Comment by rendra99** [comment]
yes it is true that there is no pure steal because it belongs to me, my
laptop for multibit very safe from the reach of the virus, so I'm please to
blockchain.info to help restore my backup .wallet that do not exist in my
laptop, I had no idea what to do let alone all the way I have done but the
results are not there, the way one of them is asking for help to
blockchaiin.info and backup .wallet multibit to find my missing after I
shut my wallet 2 days ago, I beg all to you all.
thanks please reply later further information.

**Comment by jim618** [comment]
Hi Rendra
There is no need to post the same comment twice.

Almost certainly your wallet file is still on your disk (unless you have done something like format your disk).

To get your bitcoin back you need to:
1) Find your wallet or a backup
2) Open it using File | Open wallet in MultiBit

The MultiBit help explains where wallets are stored so please go through that systematically i.e.
a) Find your application data directory. Look there.
b) Did you create your wallet in another directory ? Look there.
c) Use a backup that you created.

**Comment by rendra99** [comment]
I told you from the beginning , I did not find anything that backup wallet
after I close my wallet , so whatever I do is of no use , I 've tried all
the ways that exist in multibit but the results are not there , so if the
multibit be responsible for this incident ? I hope multibit could be
responsible for the loss of these backups , so that the user later multibit
no one was disappointed as the.
27 Mar 2015 17:34, "Jim Burton" <notifications@github.com> menulis:

**Comment by gary-rowe** [comment]
Can you verify that you have:

1. seen or not seen a wallet "vanish" after saving (malware)
1. used file recovery software as referenced in the earlier link

We cannot provide further support until you have done this.

**Comment by rendra99** [comment]
I honestly do not know about it, which I know is after I meutup my wallet
wallet backup evidence was not there and I lost access to my wallet again,
if you can not help me maybe I will willingly accept it.

**Comment by rendra99** [comment]
I honestly do not know about it, which I know is after I close my wallet
wallet backup evidence was not there and I lost access to my wallet again,
if you can not help me maybe I will willingly accept it.
