### ISSUE TITLE
Seen error message: "Another program has changed this wallet"

### ISSUE THREAD

**Issue by jay9931** [jim618/multibit#682]
Operating System:win7 64
  MultiBit Version:MultiBit 0.5.18
  Steps to replicate the problem:Another program has changed this wallet. To avoid errors this MultiBit has stopped updates

**Comment by gary-rowe** [comment]
This will occur if MultiBit detects that the wallet file has changed in size or time stamp from what it is expecting. You need to verify that you don't have another application making changes to this file. 

See this article for the file locations: https://multibit.org/en/help/v0.5/help_troubleshooting.html

**Comment by jay9931** [comment]
My wallet has tried several computers to try to recover it, but all the above error prompt! The time is right! I can not understand!

**Comment by jay9931** [comment]
![image](https://cloud.githubusercontent.com/assets/11797018/6992889/4133ad9e-db14-11e4-90e0-2f01d25b866e.png)
Even Close wallets suspended animation

**Comment by gary-rowe** [comment]
0.5.19 will tackle this in #693. 

Closing here.

**Comment by TheBritton** [comment]
I am having same issue - please advise 
Existing wallet that has worked well until now for both send and receive - Using version 0.5.18 on mac os/x. All system and Java up to date.
needing to send funds to new Multibit HD - but everytime I open Multibit, it synchs then when I hit "New" for send - it stops with the error -Another program has changed this wallet"

Moved files to a clean new mac - same issue. Rebooted - ps -ax shows no other instnce of app or java running.

At this point I cant send or even export keys !!!!

Please help , desperate times here
Paul

**Comment by jim618** [comment]
This will be fixed in version 0.5.19 which we are in the final stages of testing at the moment.
