### ISSUE TITLE
Error occurred. 

### ISSUE THREAD

**Issue by OnlyBM** [jim618/multibit#684]
Bug report:
"The user data directory is "C:\Users\Alan\AppData\Roaming\MultiBit".
The installation directory is "C:\Users\Alan\Desktop\Multibit".
Unable to load blockchain "C:\Users\Alan\AppData\Roaming\MultiBit\multibit.spvchain". The error was "com.google.bitcoin.store.BlockStoreException com.google.bitcoin.store.BlockStoreException: Header bytes do not equal SPVB".
Opening wallet "C:\Users\Alan\AppData\Roaming\MultiBit\MyWallet.wallet"...
... done.
Opening wallet "C:\Users\Alan\AppData\Roaming\MultiBit\multibit.wallet"...
... done."

  Operating System: Win 7
  MultiBit Version: Version 0.5.18
  Steps to replicate the problem: Not sure, I just recently asked someone to exchange PayPal for Bitcoin for me and he sent it to me, but it did not show up in my wallet so I assumed it must be a bug. And it displayed "ERROR" at the bottom, really hope I didn't lose $35.

**Comment by jim618** [comment]
It may be that you have a corrupted .spvchain file. See https://multibit.org/en/help/v0.5/help_support_blockStoreException.html for more details.
