### ISSUE TITLE
Bitcoins lost, Not a sign of it now..

### ISSUE THREAD

**Issue by Valdert** [jim618/multibit#685]
Hi

  Operating System: Win 8.1
  MultiBit Version: 0.5.18
  Steps to replicate the problem: I was goin to trsnfer 0.31 BTC to localbitcoins, then when I looked on the site I saw there was no "incoming transactions". So I went back to MultiBit and checked the transaction history, and the transaction was there, but a white triangle and no loading... So I decided to "Reset Blockchain and transaction" and after that, thetransaction is totally gone, just like that. They have to be somewhere, and I really hopes for some help, advice etc. 

I will be that glad if you can help me with this guys!

**Comment by Valdert** [comment]
Problem solved, It was just the time to go and then " Reset blockchain and transactions again:)

**Comment by gary-rowe** [comment]
Thanks for the update and glad it all worked out.

Closing.
