### ISSUE TITLE
MultiBit cannot Syncronize: sluggish, unmountable, freezes

### ISSUE THREAD

**Issue by antuerius** [jim618/multibit#686]
Bug Report

  Operating System: MacBook Pro 5,3 - OSX 10.6.8
  MultiBit Version: 0.5.18

Steps to replicate the problem: Read MultiBit Help and Bitcoin Stack Exchange. Multiple attempts to mount on multiple days. Mounting from restart. Modem reset. Checked correct computer Date. Tried reset Blockchain and Transactions (not possible). MultiBit freezes and will not accept menu commands, or quit (regularly requires force-quit). Attempted very long synchronize wait times, leading to freezing and required force-quit. Tried installing another replacement copy of 0.5.18 (no improvement). 

Any advisement would be much appreciated. I really like MultiBit, and would like to continue using it.

**Comment by gary-rowe** [comment]
Looks like you've tried most of the well-known solutions. Have you tried deleting the `multibit.spvchain` file? This will force a sync but may avoid problems that lead to freezes.

Can you take a look in the Messages tab and see if there are any messages appearing in there that might explain the freeze ups (perhaps there are "Exceptions" or memory problems).

**Comment by antuerius** [comment]
Thank-you for your advice. As per your advice, tried removing the spvchain file, and restarted. MultiBit started a little better; but took hours to reset. After resetting and at long last, a complete syncronization, the ware was still dysfunctionally sluggish. There was an opportunity to select "Reset Blockchain and Transactions", which worked; yet took a very long time. Afterwards, all my BTC was showing in healthy fashion. MultiBit was still uncharacteristically sluggish and largely inoperable. 
I checked the messages tab documentation and did not see any Exceptions, or memory problems. I will try it a few more times; but improvement doesn't really intuit as probable thus far. 

Any further suggestions or insights are appreciated.

**Comment by antuerius** [comment]
Verfied and Repaired drive. All other programs work well. Still no charm. Deleting spvch and restarting has produced a full mount, on the long term, at least once more; yet the sluggish operability flips pinwheels at every command click. I would like to move my BTC to my blockchain account until there is luck; or before it gets worse. Cannot manage to discover enough operability from Multibit to secure BTC. My Multibit wallet is password protected.

**Comment by jim618** [comment]
It sounds like moving your wallet to blockchain.info is a good idea for you.
There is a support note on how to do this here:
https://multibit.org/en/help/v0.5/help_movingAWallet.html

Let us know if anything is unclear but it should be fairly straightforward.

**Comment by antuerius** [comment]
Export copy paste function is too wobbly for success. Maybe an internal verify and repair wasn't enough. Typically use Disk Warrior, and expect this drive is scrambled on Multibit territory. DW released a new upgrade; so that and this, will have to wait. Thanks for your advice.

**Comment by antuerius** [comment]
I should add that after Multibit slow-syncs it almost regularly stops itself, with the message that "an external program has altered this (something)" and Multibit is "stopping updates". Is this virus territory?

**Comment by gary-rowe** [comment]
Some excellent information in this issue, many thanks for @antuerius for the effort in recording it.

#693 may fix this and is scheduled for 0.5.19. Closing this here.
