### ISSUE TITLE
Status keeps on saying "Connecting..." on testing

### ISSUE THREAD

**Issue by rollyD** [jim618/multibit#691]
I've change the multibit properties. I've set the "testOrProductionNetwork" to "test" and "testnet3" but none of them work. It keeps on saying "connecting..." but if I'm going to change the value to "production" then it is successfully connecting. May I know what will be the possible solution that I can do. Thank you very much in advance!

**Comment by gary-rowe** [comment]
TestNet can be quite flaky - you probably just hit it at a bad time. Best to stick with MainNet really.

Closing.
