### ISSUE TITLE
How to open MultiBit from backup?

### ISSUE THREAD

**Issue by zenontherocks** [jim618/multibit#695]
I had some issues with my computer, but I was able to recover my files. Now I need to know how to open MultiBit and transfer my bitcoins without it being on my apps list. I'm sure this is a very simple thing I just don't know how to do it. Help please?

EDIT: I see that there's a .jar there, it seems to be the only executable. But when I go to "properties" > "permissions" > "allow executing file as program", the checkbox goes on and then goes right back off.

**Comment by jim618** [comment]
When you have an installation of MultiBit, you have two directories where things are stored:
+ Where the program (the jar file you found) is stored
+ Where the wallet is stored.

It's the wallet you need to access your bitcoins. You can always reinstall the MultiBit program if you need to.

The wallet file is typically called 'multibit.wallet' (unless you've chosen a specific file). You can simply open it using 'File | Open wallet' and it will synchronize.

There is quite a lot more in the help which is worth reading:
https://beta.multibit.org/en/help/v0.5/help_troubleshooting.html
and
https://beta.multibit.org/en/help/v0.5/help_fileDescriptions.html

**Comment by zenontherocks** [comment]
Thanks Jim! I think that's what I was missing. I ended up opening the .jar in Windows, pointing it to my wallet, then letting it sync overnight and viola! There were my coins!
