### ISSUE TITLE
Updates Stopped issue.

### ISSUE THREAD

**Issue by suwenxu** [jim618/multibit#698]
Bug report
  Operating System: Windows 8.1 Single Language with Bing, 32 bits OS, x64-based processor
  MultiBit Version: v0.5.18
  Steps to replicate the problem: 

1. After having imported password-protected private key into new multibit client in new pc, Updates Stopped issue happened when I tried to send bitcoin.

2. Wanted to try solution of moving wallet to blockchain, however, old pc had been formatted and thus, I cannot export another private key which is NOT password protected.

Question: When will the program be updated as this is clearly the bug of software?

**Comment by jim618** [comment]
If you've got an encrypted export of your private keys you can decrypt it using openssl.
The details are here (at the bottom):
https://github.com/jim618/multibit/wiki/Export%20and%20limited%20import%20of%20private%20keys

Then you'll have your private keys in cleartext to import somewhere else.

**Comment by suwenxu** [comment]
Hi jim618,

Thank you for your reply, could you please show me the detailed steps on how-to-do to decrypt private key using openssl on windows as I'm totally clueless in this?

**Comment by suwenxu** [comment]
Hi jim618,

I managed to get back bitcoins using the method given by you, SINCERELY THOUSANDS OF THANKS TO YOU AND YOUR TEAM! THANK YOU VERY MUCH!

p/s: Hope that "updates stopped" problem will be fixed as soon as possible. =)

**Comment by gary-rowe** [comment]
@suwenxu Glad you were able to get your bitcoins back. We're planning a maintenance release of MultiBit Classic after [MultiBit HD](https://beta.multibit.org) Release 0.1 is finalised.
