### ISSUE TITLE
i have a problem,  btc don't arrive

### ISSUE THREAD

**Issue by nachete261** [jim618/multibit#699]
hello ,
Software OS X 10.8.5 
multibitt v  5.18
problems:
 yesterday i created a multibit  btc account and i passed some btc to new my  account and never arrived it. in bockchain is all right. this is my account 1J5NdTaNGjvzS4HXFjL3GAhZpHW5SA5M1y
do you know what is happening?

thanks and best regards

**Comment by jim618** [comment]
Hello Nachete,
Can you confirm that you have read the support note which covers this please:
https://multibit.org/en/help/v0.5/help_support_sentBitcoinToMultibitButTheyNeverArrived.html

**Comment by nachete261** [comment]
yes i read, i understand little english .
i have more accounts and  not problem, do you know what is happening with this account? 

thanks and best regards

**Comment by nachete261** [comment]
its solver man . thanks and best regards
