### ISSUE TITLE
I send bitcoin from MultiBit but they are stuck

### ISSUE THREAD

**Issue by bharaian** [jim618/multibit#706]
In the '  Transactions' tab the transaction is shown with a triangle and it does not found on https://blockchain.info/tx-index/101f5f6f3f134f0cd27d679f29f56fc10e208d80949ee9065455bc2de410b460.

I have follow the sequence in the help section but could not get any where and I have screen shoot. 

How can i get my money back ?

**Comment by jim618** [comment]
Can you confirm that you have worked through the support article covering this:
https://multibit.org/en/help/v0.5/help_support_sentBitcoinFromMultibitButTheyAreStuck.html

If you run through this the transaction that was not transmitted should disappear from your copy of MultiBit and any bitcoin involved in the transaction will be available again.

**Comment by bharaian** [comment]
Yes jim618, I have gone through all this https://multibit.org/en/help/v0.5/help_support_sentBitcoinFromMultibitButTheyAreStuck.html process unfortunatly no funds retrieved and nothing disappear from transactions and luckly took some screenshoot for that when i follow process.

**Comment by jim618** [comment]
Can you confirm that you:
1) Did a reset blockchain and transactions
2) After it completed and the wallet synced you still saw a transaction with a triangle
?

**Comment by bharaian** [comment]
yes i can confirm that the transaction still there with triangle can send screenshoot to see that its still there.

**Comment by jim618** [comment]
Did you do a Tools | Reset blockchain and transactions and the wallet successfully synced ?
The reset clears all the transactions in the wallet when it runs is why I ask.

**Comment by bharaian** [comment]
yes Jim i completly understand your question and that is why i answer. i was thinking to do it again but stop to take good advise or help to get my funds back

**Comment by bharaian** [comment]
it seems i must reset all transaction which may help me to get back my funds

**Comment by jim618** [comment]
It is safe to do it again - the 'Tools | Reset blockchain and transactions' simply synchronises your local wallet to what is on the global blockchain

**Comment by bharaian** [comment]
i just done and the transaction with triangle is disappear completly and NO FUNDS back .

**Comment by jim618** [comment]
If you have successfully done a 'Reset blockchain and transactions' your wallet should now be synced with the blockchain.
The transaction that was not sent, which is not on the blockchain, is no longer present in your wallet. This is how it should be.
The balance on your wallet should now be the total of your unspent transactions.

**Comment by bharaian** [comment]
some screenshoot 
![abc1](https://cloud.githubusercontent.com/assets/13156862/8502584/d7e5ed5c-21a9-11e5-8c37-3b69ca934e66.png)
![abc7](https://cloud.githubusercontent.com/assets/13156862/8502583/d7e4e4e8-21a9-11e5-8668-618aa9fbf47d.png)

I did not got my money back. I have lost $2500+

**Comment by bharaian** [comment]
![abc8](https://cloud.githubusercontent.com/assets/13156862/8502618/679b2da4-21aa-11e5-83c4-47f999b67359.png)
Jim, just done reset again as per your advise and see result.

**Comment by jim618** [comment]
As long as you have control of your private keys (and no-one else has them) you cannot really lose your bitcoins.

If you want a second opinion as to the transactions on the blockchain that are available to spend for your addresses/ private keys i suggest you move them to blockchain.info

You can effectively make a clone of your wallet using blockchain.info's data.

There is a detailed set of instructions here:
https://multibit.org/en/help/v0.5/help_movingAWallet.html

**Comment by jim618** [comment]
On your transactions screen all the transactions visible are sed to the address: 17bmVFKVRgLi55pAG6yYMZmcY1HWToRTyB

If you look up the current balance on that address in blockchain.info you can see that it is zero bitcoins:
https://blockchain.info/address/17bmVFKVRgLi55pAG6yYMZmcY1HWToRTyB

(the final balance is in the header section, right hand side)
