### ISSUE TITLE
Lost Bitcoins

### ISSUE THREAD

**Issue by FileTransferProtocol** [jim618/multibit#707]
Sent Bitcoins to a wallet and since it took so long to transfer the funds I reset the wallets blockchain and now the Bitcoins sent are gone without record of the previous balance.  

 Bug report
  Operating System: Mac Osx 10.8.5
  MultiBit Classic Version: 0.5.18
  Steps to replicate the problem:
1. Send BTC  
2. No peers had seen the tx
3. 45min - 1 hour pass
4. reset wallet blockchain 
5. btc are gone and no record of previous balance before sending funds.

around 0.1047BTC $28 at this time.
Funds where from this wallet 1CBZNrpWbFJ6iAGeAJNdgxFDnV4ETwd32z

funds where supposed to go to 12oHGaVL97vq7B3DF36DukdgP9BxNpJiGK

Ok now I can see the balance that I am supposed to have 
<img width="1416" alt="screen shot 2015-07-07 at 10 47 35 pm" src="https://cloud.githubusercontent.com/assets/10070550/8563937/5b5feb4e-24fa-11e5-90db-b6f6afa537f1.png">
but my multi bit wallet does not acknowledge.
<img width="1178" alt="screen shot 2015-07-07 at 10 47 47 pm" src="https://cloud.githubusercontent.com/assets/10070550/8563939/60178b1a-24fa-11e5-90d4-b49d6f826d41.png">

**Comment by FileTransferProtocol** [comment]
it fixed itself

**Comment by jim618** [comment]
Good to hear.
The stress test with ten of thousands of transactions flying around has made confirmations quite problematic of late.
