### ISSUE TITLE
Bitcoin transaction stuck unverified

### ISSUE THREAD

**Issue by Cactus77** [jim618/multibit#709]
I tried sending a small amount of coins to my exchange account yesterday and it is stuck. 
It shows the transaction in the transactions list and it has a circle. Today it was showing the same thing and it said seen by 28 peers with the same white circle, unconfirmed. So, I did a reset and yes I also tried closing the wallet and reopening. After the blockchain reset it still showed the white circle with unconfirmed status but the number of peers seen changed. It now says seen by 11 peers. Here is the blockchain.info link to this transaction. 

https://blockchain.info/tx-index/bc52711fa4db028d283324e16b7179ca8ef9e8ebed9632ebdeab55d844135104 

What's going on?

**Comment by jim618** [comment]
Most likely this is due to the large number of unconfirmed transactions in the Bitcoin network.
You can see the overall status at, say, https://tradeblock.com/blockchain

I just looked and there are 90,000 transactions waiting to be confirmed.
Not much to do other than be patient for the miners' to mine it I am afraid.

**Comment by Cactus77** [comment]
So the question then is does it normally take 2 days to get through that long line of transactions? And why would it go from 28 peers seen to 11 after a reset? Strange...

**Comment by Cactus77** [comment]
It finally went through as of today. It took being seen by 30 peers before it was confirmed while other transactions are confirmed after only 1 or 2 peers, according to the 'see more details' about this transaction. Thanks for your help Jim and I've got to say that I really LIKE Multibit for my wallet. It's what I've always used since the beginning. Have a good one!

**Comment by jim618** [comment]
Thanks for your feedback !
