### ISSUE TITLE
Can't open my wallet

### ISSUE THREAD

**Issue by oscarmo327** [jim618/multibit#711]
I didn't open MultiBit since last year. However, when I want to open MultiBit today, I found that I can't open my wallet even I had backup file. It seems that I can't fully synchronized. Does anyone can help me to solve the problem? Thank you very much!
![image](https://cloud.githubusercontent.com/assets/13310407/8644812/d16d81e2-2974-11e5-89c2-918d5a64f702.png)

**Comment by gary-rowe** [comment]
Could be a network problem. Can you verify you've read this article:

https://multibit.org/en/help/v0.5/help_support_network.html

**Comment by gary-rowe** [comment]
Were you able to resolve the problem?

**Comment by oscarmo327** [comment]
Yes. Thank you very much. I just transfer my Bitcoin to blockchain

Gary Rowe <notifications@github.com> 於 2015年7月23日星期四 寫道：

**Comment by gary-rowe** [comment]
Thanks for the update. You might want to try out [MultiBit HD](https://multibit.org) which offers much better network handling.

Closing.

**Comment by oscarmo327** [comment]
Thank you for your help!

Gary Rowe <notifications@github.com> 於 2015年7月23日星期四 寫道：
