### ISSUE TITLE
passphrase mismatch with import/export

### ISSUE THREAD

**Issue by saivann** [jim618/multibit#88]
Multibit 0.4.23, Ubuntu 12.04

Exported encrypted keys with multibit cannot be decrypted with openssl when passphrase contains a dot (.) or other special characters. Except when the passphrase is pasted from clipboard.

Steps to reproduce :

1. Export multibit keys with passphrase : test-
2. Try to decrypt keys with open ssl : openssl enc -d -p -aes-256-cbc -a -in <ciphertext file> -pass pass:test-

Result : Fails. The exported keys can still be imported in multibit. They can just not be decrypted using openssl.

However, this works :

1. Export multibit keys with passphrase : test
2. Try to decrypt keys with open ssl : openssl enc -d -p -aes-256-cbc -a -in <ciphertext file> -pass pass:test

Result : Works

1. Type "test-" in gedit text editor and copy to clipboard.
1. Export multibit keys and paste the passphrase instead of typing it.
2. Try to decrypt keys with open ssl : openssl enc -d -p -aes-256-cbc -a -in <ciphertext file> -pass pass:test-

Result : Works

According to this, it seems that multibit converts some characters when they are typed, and not when they are pasted.

**Comment by gary-rowe** [comment]
Closing as MBHD has been using a consistent charset for some time now.
